language: python
python:
  - "3.7-dev"

install:
  - pip install pylint
script:
  - python -c 'import sys; print(sys.path)'
  - python tests/test_sum.py
after_success:
  - pylint sum.py
  - pylint tests/test_sum.py
